### ISSUE TITLE
Using ellipsoids instead of spheres

### ISSUE THREAD

**Issue by ttsesm** [AntonSemechko/S2-Sampling-Toolbox#2]
Hi @AntonSemechko,

Thanks for sharing your code. I have a question though, is it possible to apply the functionality of the S2-Sampling-Toolbox for ellipsoids instead of spheres?

I would like to split the surface of an ellipsoid in a grid of cells of equal area or points that are equidistant and I was wondering whether it is possible this to be done with your toolbox.

I guess using the `SpiralSampleSphere.m` might be more suitable to be modified and used? 

Thanks.

**Comment by AntonSemechko** [comment]
Hi @ttsesm,

This toolbox does not support uniform sampling of non-spherical surfaces. However, the particle-based sampling function can be modified to produce that functionality.  I will be adding another toolbox in the near future that will have that function.

In the meantime, if you tell me the dimensions of the principal axes, target sampling density (or number of points), and number of subdivision levels you want in the target mesh of the ellipsoid, I can post it here.

**Comment by ttsesm** [comment]
Hi @AntonSemechko,

Thanks for the swift answer and apologies for the late response.

Well, the principal axes, density and number of subdivision levels in the target mesh should be given as parameters. Thus, I do not have any specific numbers that I am interested. In principle, for my tests I have multiple ellipsoids of different sizes (i.e. principal axes) and orientations. Then for each one of them I guess I can have a fixed number of points and subdivisions, right?
